site_name: Outback Robots Resource Hub
site_url: https://outbackrobots.github.io/Outback-Robots-Hub/

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.tracking # track scroll position
    - navigation.path # highlight current section in navigation
    - navigation.indexes # show index pages in navigation
    - navigation.sections # show section headers in navigation
    - navigation.prune # only show navigation items with content
    - navigation.top # add "top" link to navigation
    - navigation.tabs
    - navigation.tabs.sticky # keep tabs visible when scrolling
    - header.autohide # hide header on scroll down, show on scroll up
    - toc.follow
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: green
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - stylesheets/custom.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: false
  - macros
  - mkdocs-pdf

nav:
  - Home: index.md
  - Lessons:
      - Overview: units/core/index.md
      - Lesson 1: units/core/lessons/lesson01/index.md
      - Lesson 2: units/core/lessons/lesson02/index.md
      - Lesson 3: units/core/lessons/lesson03/index.md
      - Lesson 4: units/core/lessons/lesson04/index.md
      - Lesson 5: units/core/lessons/lesson05/index.md
      - Lesson 6: units/core/lessons/lesson06/index.md
      - Lesson 7: units/core/lessons/lesson07/index.md
      - Lesson 8: units/core/lessons/lesson08/index.md
  - Blossom: blossom/index.md
#  - Activities:
#      - Overview: activities/index.md
#      - Template: _templates/activity_template.md
#  - Glossary:
#      - Overview: glossary/index.md
#      - Template: _templates/keyterm_template.md
#  - Help & Quick Fixes: help/index.md
#  - Changelog: changelog.md

